# Generated by Django 4.2.16 on 2024-09-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workpackage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpackage',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
