# Generated by Django 4.2.16 on 2024-09-16 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
        ('workpackage', '0002_alter_workpackage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.task')),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workpackage.workpackage')),
            ],
        ),
    ]
