# Generated by Django 5.1.1 on 2024-11-10 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_project_name'),
        ('workpackage', '0006_alter_measurement_height_alter_measurement_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workpackages', to='tasks.project'),
            preserve_default=False,
        ),
    ]
