# Generated by Django 4.2.16 on 2024-09-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
